import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from '../providers/QueryProvider';
import CustomThemeProvider from '@/providers/ThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomThemeProvider>
          <QueryProvider>
            <main className="px-40 py-20">{children}</main>
          </QueryProvider>
        </CustomThemeProvider>
      </body>
    </html>
  );
}
